# Generated by Django 2.0.2 on 2019-01-23 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='directorytree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.IntegerField()),
                ('name', models.CharField(max_length=254)),
                ('key', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='itbody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body_format', models.SmallIntegerField()),
                ('type', models.CharField(max_length=50)),
                ('desc', models.CharField(default=None, max_length=254, null=True)),
                ('value', models.TextField()),
                ('upload_file', models.CharField(default=None, max_length=100, null=True)),
                ('body_type', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='itheader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=254)),
                ('type', models.CharField(default=None, max_length=10, null=True)),
                ('desc', models.CharField(default=None, max_length=254, null=True)),
                ('header_type', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='itlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('log_path', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='itparam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=254)),
                ('type', models.CharField(default=None, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='itstatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('protocol_type', models.CharField(max_length=10)),
                ('request_type', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=100)),
                ('desc', models.CharField(default=None, max_length=254, null=True)),
                ('status', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('requestparam', models.CharField(max_length=100)),
                ('expectres', models.CharField(max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(default=None, max_length=254, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tagmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('status', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('tags', models.CharField(default=None, max_length=254, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface_platform.directorytree')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='testcaselog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('log_path', models.CharField(max_length=254)),
                ('tc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface_platform.testcase')),
            ],
        ),
        migrations.CreateModel(
            name='testcasestep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('it', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface_platform.itstatement')),
                ('tc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface_platform.testcase')),
            ],
        ),
        migrations.CreateModel(
            name='testsuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('rerun', models.SmallIntegerField()),
                ('passednum', models.IntegerField()),
                ('failednum', models.IntegerField()),
                ('skippednum', models.IntegerField()),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface_platform.testcase')),
            ],
        ),
        migrations.CreateModel(
            name='testsuite_test_cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface_platform.testcase')),
                ('testsuite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface_platform.testsuite')),
            ],
        ),
        migrations.CreateModel(
            name='uniid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='interface_platform.itstatement')),
                ('tc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='interface_platform.testcase')),
                ('test_suite', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='interface_platform.testsuite')),
            ],
        ),
        migrations.CreateModel(
            name='variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(default=None, max_length=254, null=True)),
                ('value', models.CharField(max_length=254)),
                ('type', models.CharField(max_length=100)),
                ('mark', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface_platform.project')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='variableit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assoc_type', models.CharField(default=None, max_length=100, null=True)),
                ('assoc_id', models.IntegerField(default=None, null=True)),
                ('it', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface_platform.itstatement')),
                ('var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface_platform.variable')),
            ],
        ),
        migrations.AddField(
            model_name='tagmap',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface_platform.testcase'),
        ),
        migrations.AddField(
            model_name='tagmap',
            name='tc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface_platform.tag'),
        ),
        migrations.AddField(
            model_name='itstatement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface_platform.project'),
        ),
        migrations.AddField(
            model_name='itstatement',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itparam',
            name='it',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface_platform.itstatement'),
        ),
        migrations.AddField(
            model_name='itlog',
            name='it',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface_platform.itstatement'),
        ),
        migrations.AddField(
            model_name='itheader',
            name='it',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface_platform.itstatement'),
        ),
        migrations.AddField(
            model_name='itbody',
            name='it',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface_platform.itstatement'),
        ),
        migrations.AddField(
            model_name='directorytree',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface_platform.project'),
        ),
    ]
